id: P001757
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20141
  title: གསོ་བྱེད་ཐབས་ཀྱི་རྣམ་བཤད།
  author: ''
  volumes:
    8e55e39989804ef4b9aab8ffd11d89c5:
      image_group_id: I4770
      title: ''
      volume_number: 1
      total_pages: 299
      base_file: v001.txt
